### ISSUE TITLE
04/19/2024 TAS RUN speedrun-beta branch

### ISSUE THREAD

**Issue by Eein** [shenef/SoS-TAS#238]
doing a tas run: (bugs)
- falls off dropping platform in bosslug dungeon (mountain trail? idr)
- level up window ... sometimes works - its not flipping over when level up is on and getting stuck trying to pick ...something, may be getting stuck in some state or something or something needs to be reset when the flag pops
- valere uses cresent arc on elder mist even though its the only thing alive
- stuck on solstice ring chest in XtolsLanding
- got hit by boomerang on sleeper island
- windtunnel mines, kind of stops until you jump down to the lower floor after elevators fixed
- stuck on a ledge in wizard lab, move slightly left to fix
j- umps in blue crystal room second time caught - moved slightly right to fix

on death
```
[01:17:30.668] engine.combat.utility.sos_appraisal DEBUG    Confirming Enemy 12d283ff-433f-45da-8a64-5d20e952912c
[01:17:31.935] engine.combat.utility.sos_appraisal DEBUG    Executing Timing Attack, Tap (Attack)
[01:17:32.041] engine.combat.utility.sos_appraisal DEBUG    Action Complete
[01:17:35.856] engine.combat.controllers.encounter_controller DEBUG    Spam Block for ArenteeDiveBomb Attack
[01:17:40.206] engine.combat.controllers.encounter_controller INFO     New action: Zale->Attack (target = Arentee [0]) boost=1
[01:17:40.226] engine.combat.utility.sos_appraisal DEBUG    Boosting: Attack 1 times
[01:17:40.726] engine.combat.utility.sos_appraisal DEBUG      Triggering Boost: 1
[01:17:41.142] engine.combat.utility.sos_appraisal DEBUG    Confirmed Battle Command: Attack
[01:17:41.148] engine.combat.utility.sos_appraisal DEBUG    Selected Target 12d283ff-433f-45da-8a64-5d20e952912c
[01:17:41.154] engine.combat.utility.sos_appraisal DEBUG    Confirming Enemy 12d283ff-433f-45da-8a64-5d20e952912c
[01:17:42.466] engine.combat.utility.sos_appraisal DEBUG    Executing Timing Attack, Tap (Attack)
[01:17:42.573] engine.combat.utility.sos_appraisal DEBUG    Action Complete
[01:17:46.746] engine.combat.controllers.encounter_controller DEBUG    Spam Block for BoulbeSeedCannon Attack
Traceback (most recent call last):
  File "/home/will/code/sea-of-stars/SoS-TAS/main.py", line 59, in <module>
    menu_manager.run()
  File "/home/will/code/sea-of-stars/SoS-TAS/GUI/menu.py", line 58, in run
    self.window.start_frame()
  File "/home/will/code/sea-of-stars/SoS-TAS/GUI/GUI.py", line 140, in start_frame
    self.update(delta)
  File "/home/will/code/sea-of-stars/SoS-TAS/GUI/TASWindow.py", line 44, in update
    combat_manager_handle().update()
  File "/home/will/code/sea-of-stars/SoS-TAS/memory/combat_manager.py", line 163, in update
    self._read_battle_commands()
  File "/home/will/code/sea-of-stars/SoS-TAS/memory/combat_manager.py", line 514, in _read_battle_commands
    battle_command_selector = self.memory.follow_pointer(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/will/code/sea-of-stars/SoS-TAS/memory/core.py", line 119, in follow_pointer
    addr = self.read_longlong(addr + offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/will/code/sea-of-stars/SoS-TAS/memory/core.py", line 262, in read_longlong
    returned_bytes = pyMeow.r_bytes(self.pm, address, struct.calcsize("q"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nimpy.AccessViolationDefect: Unexpected error encountered: readSeq failed [Address: 0x0000000000000140] [Error: 14 - Bad address]
(venv)
```

**Comment by Eein** [comment]
Check for information about skipping cutscenes but also the event that is playing so we can blacklist
